#!/bin/bash

array=( "$@" )
token=()
replace=" = "
equal="="
space=" "
dquote='"'

for a in "${array[@]}"; do
	if [[ "$a" == *$equal* ]]; then
		a=$(echo "$a" | tr " " "|")
		a=${a/=/$replace}
		sub=(${a/ / })
		for s in "${sub[@]}"; do
			s=$(echo "$s" | tr "|" " ")
			if [[ "$s" == *$space* ]]; then
				s=$dquote$s$dquote
			fi
			token+=("$s")
		done
	else
		token+=("$a")
	fi
done

javac src/dataStore/*.java
java -cp src/ dataStore.Main "${token[@]}"
